In [1]:
import warnings
import pandas as pd
from pathlib import Path

In [2]:
# File Path
school_metrics_data_to_load = Path("data/SPREE_SY2223_School_Metric_Scores.csv")

# Read shcool metrics into Pandas DataFrames
school_metrics_data = pd.read_csv(school_metrics_data_to_load)

In [3]:
school_metrics_data.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
0,2022-2023,1010,John Bartram High School,High School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1,2022-2023,1010,John Bartram High School,High School,% of Students Attending Less Than 80% of Instr...,292.0,617.0,47.3,NaN,NaN,NaN
2,2022-2023,1010,John Bartram High School,High School,% of Students Attending 80-85% of Instructiona...,51.0,617.0,8.3,NaN,NaN,NaN
3,2022-2023,1010,John Bartram High School,High School,% of Students Attending 85-90% of Instructiona...,66.0,617.0,10.7,NaN,NaN,NaN
4,2022-2023,1010,John Bartram High School,High School,% of Students Attending at Least 90% of Instru...,208.0,617.0,33.7,33.8,-0.1,Maintaining

In [4]:
school_metrics_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83980 entries, 0 to 83979
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  83980 non-null  object
 1   school_id            83980 non-null  int64
 2   school_name          83980 non-null  object
 3   report_type          83980 non-null  object
 4   metric               83980 non-null  object
 5   numerator            20464 non-null  float64
 6   denominator          17254 non-null  float64
 7   metric_score         83980 non-null  object
 8   score_previous       71701 non-null  object
 9   score_change         71706 non-null  object
 10  tier                 11507 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 7.0+ MB

In [5]:
# Calculate and print the number of schools
schools_count = school_metrics_data['school_id'].nunique()
print("Number of unique schools:",schools_count)

# List the unique school ids
unique_ids = school_metrics_data['school_id'].unique()
# print("Number of unique school IDs:",unique_ids)

Number of unique schools: 294

In [6]:
#Calculate and print the number of school names
school_name_count = school_metrics_data['school_name'].nunique()
print("Number of unique schools:",school_name_count)

# List the unique school names
unique_names = school_metrics_data['school_name'].unique()
# print("Number of unique school names:",unique_names)

Number of unique schools: 294

In [7]:
#Calculate and print the number of unique metrics
metrics_count=school_metrics_data['metric'].nunique()
print("Number of unique metrics:",metrics_count)

# List the unique metrics
unique_metrics = school_metrics_data['metric'].unique()
# unique_metrics

Number of unique metrics: 260

In [8]:
#Calculate and print the number of Report Types
report_types_count = school_metrics_data['report_type'].nunique()
print("Number of report types:",report_types_count)

# List the Report Types
unique_reports = school_metrics_data['report_type'].unique()
print("Report Types:", unique_reports)

Number of report types: 4
Report Types: ['High School' 'Middle School' 'K-8 School' 'Elementary School']

In [9]:
# Identify duplicates based on 'school_id' and 'metric'
duplicates = school_metrics_data[school_metrics_data.duplicated(subset=['school_id', 'metric'], keep=False)]
duplicate_school_count = duplicates['school_name'].nunique()
print("Number of duplicate School IDs:", duplicate_school_count)

# List the Duplicate Schools
duplicate_schools = duplicates['school_name'].unique()
# print("Duplicate Schools:", duplicate_schools)

Number of duplicate School IDs: 29

In [10]:
# Create the 'High School' 'Middle School' 'K-8 School' 'Elementary School' dataframes
high_school_metrics_df = school_metrics_data.loc[school_metrics_data['report_type'] == 'High School']
middle_school_metrics_df = school_metrics_data.loc[school_metrics_data['report_type'] == 'Middle School']
ktoeight_school_metrics_df = school_metrics_data.loc[school_metrics_data['report_type'] == 'K-8 School']
elementary_school_metrics_df = school_metrics_data.loc[school_metrics_data['report_type'] == 'Elementary School']

# Check for duplicates
high_school_duplicates = high_school_metrics_df[high_school_metrics_df.duplicated(subset=['school_id', 'metric'], keep=False)]
duplicate_high_school_count = high_school_duplicates['school_name'].nunique()
middle_school_duplicates = middle_school_metrics_df[middle_school_metrics_df.duplicated(subset=['school_id', 'metric'], keep=False)]
duplicate_middle_school_count = middle_school_duplicates['school_name'].nunique()
ktoeight_school_duplicates = ktoeight_school_metrics_df[ktoeight_school_metrics_df.duplicated(subset=['school_id', 'metric'], keep=False)]
duplicate_ktoeight_school_count = ktoeight_school_duplicates['school_name'].nunique()
elementary_school_duplicates = elementary_school_metrics_df[elementary_school_metrics_df.duplicated(subset=['school_id', 'metric'], keep=False)]
duplicate_elementary_school_count = elementary_school_duplicates['school_name'].nunique()

print("Number of duplicate High Schools:", duplicate_high_school_count)
print('-' * 40)
print("Number of duplicate Middle Schools:", duplicate_middle_school_count)
print('-' * 40)
print("Number of duplicate K-8 Schools:", duplicate_ktoeight_school_count)
print('-' * 40)
print("Number of duplicate Elementary Schools:", duplicate_elementary_school_count)

Number of duplicate High Schools: 0
----------------------------------------
Number of duplicate Middle Schools: 0
----------------------------------------
Number of duplicate K-8 Schools: 0
----------------------------------------
Number of duplicate Elementary Schools: 0

In [11]:
# Calculate the number of school names
high_school_count = high_school_metrics_df['school_name'].nunique()
middle_school_count = middle_school_metrics_df['school_name'].nunique()
ktoeight_school_count = ktoeight_school_metrics_df['school_name'].nunique()
elementary_school_count = elementary_school_metrics_df['school_name'].nunique()

# Print info for the dataframes 
print("Number of High Schools:", high_school_count)
high_school_metrics_df.info()
print('-' * 60)
print("Number of Middle Schools:", middle_school_count)
middle_school_metrics_df.info()
print('-' * 60)
print("Number of K-8 Schools:", ktoeight_school_count)
ktoeight_school_metrics_df.info()
print('-' * 60)
print("Number of Elementary Schools:", elementary_school_count)
elementary_school_metrics_df.info()
print('-' * 60)
all_schools = high_school_count + middle_school_count + ktoeight_school_count + elementary_school_count
print("Number of Schools:", all_schools)

Number of High Schools: 84
<class 'pandas.core.frame.DataFrame'>
Index: 21840 entries, 0 to 83719
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  21840 non-null  object
 1   school_id            21840 non-null  int64
 2   school_name          21840 non-null  object
 3   report_type          21840 non-null  object
 4   metric               21840 non-null  object
 5   numerator            4719 non-null   float64
 6   denominator          3879 non-null   float64
 7   metric_score         21840 non-null  object
 8   score_previous       18647 non-null  object
 9   score_change         18648 non-null  object
 10  tier                 1158 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 2.0+ MB
------------------------------------------------------------
Number of Middle Schools: 29
<class 'pandas.core.frame.DataFrame'>
Index: 7540 entries, 1300 to 77739
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  7540 non-null   object
 1   school_id            7540 non-null   int64
 2   school_name          7540 non-null   object
 3   report_type          7540 non-null   object
 4   metric               7540 non-null   object
 5   numerator            1574 non-null   float64
 6   denominator          1284 non-null   float64
 7   metric_score         7540 non-null   object
 8   score_previous       6437 non-null   object
 9   score_change         6438 non-null   object
 10  tier                 927 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 706.9+ KB
------------------------------------------------------------
Number of K-8 Schools: 154
<class 'pandas.core.frame.DataFrame'>
Index: 40040 entries, 1820 to 83979
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  40040 non-null  object
 1   school_id            40040 non-null  int64
 2   school_name          40040 non-null  object
 3   report_type          40040 non-null  object
 4   metric               40040 non-null  object
 5   numerator            10476 non-null  float64
 6   denominator          8956 non-null   float64
 7   metric_score         40040 non-null  object
 8   score_previous       34185 non-null  object
 9   score_change         34188 non-null  object
 10  tier                 7009 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 3.7+ MB
------------------------------------------------------------
Number of Elementary Schools: 56
<class 'pandas.core.frame.DataFrame'>
Index: 14560 entries, 2340 to 82939
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  14560 non-null  object
 1   school_id            14560 non-null  int64
 2   school_name          14560 non-null  object
 3   report_type          14560 non-null  object
 4   metric               14560 non-null  object
 5   numerator            3695 non-null   float64
 6   denominator          3135 non-null   float64
 7   metric_score         14560 non-null  object
 8   score_previous       12432 non-null  object
 9   score_change         12432 non-null  object
 10  tier                 2413 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 1.3+ MB
------------------------------------------------------------
Number of Schools: 323

In [12]:
high_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
0,2022-2023,1010,John Bartram High School,High School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1,2022-2023,1010,John Bartram High School,High School,% of Students Attending Less Than 80% of Instr...,292.0,617.0,47.3,NaN,NaN,NaN
2,2022-2023,1010,John Bartram High School,High School,% of Students Attending 80-85% of Instructiona...,51.0,617.0,8.3,NaN,NaN,NaN
3,2022-2023,1010,John Bartram High School,High School,% of Students Attending 85-90% of Instructiona...,66.0,617.0,10.7,NaN,NaN,NaN
4,2022-2023,1010,John Bartram High School,High School,% of Students Attending at Least 90% of Instru...,208.0,617.0,33.7,33.8,-0.1,Maintaining

In [13]:
# list all the high school metrics
hs_unique_metrics = high_school_metrics_df['metric'].unique()
hs_unique_metrics

array(['Admission Type',
       '% of Students Attending Less Than 80% of Instructional Days',
       '% of Students Attending 80-85% of Instructional Days',
       '% of Students Attending 85-90% of Instructional Days',
       '% of Students Attending at Least 90% of Instructional Days',
       '% of Students Attending 90-95% of Instructional Days',
       '% of Students Attending at Least 95% of Instructional Days',
       'Number of Dropouts - Last School of Touch (Grades 7-12)',
       '# of Students Served Over the Full Year', 'October 1 Enrollment',
       '% of Students Who Are American Indian/Alaskan Native',
       '% of Students Who Are Asian',
       '% of Students Who Are Black/African American',
       '% of Students Who Are Economically Disadvantaged',
       '% of Students Who Are English Learners',
       '% of Students Who Are Hispanic/Latino',
       '% of Students Who Are Multiracial',
       '% of Students Who Are Native Hawaiian/Alaskan Native',
       '% of Students Who Are Special Education',
       '% of Students Who Are White',
       '% of Students Completing the FAFSA by End of 12th Grade',
       'First-Fall Matriculation', 'Score Level,  All Students',
       'Score Level,  American Indian/Alaskan Native',
       'Score Level,  Asian', 'Score Level,  Black/African American',
       'Score Level,  Economically Disadvantaged',
       'Score Level,  English Learners', 'Score Level,  Hispanic/Latino',
       'Score Level,  Multiracial',
       'Score Level,  Native Hawaiian/Pacific Islander',
       'Score Level,  Special Education', 'Score Level,  White',
       'Four-Year Cohort Graduation Rate',
       'Four-Year Cohort Graduation Rate, American Indian/Alaskan Native',
       'Four-Year Cohort Graduation Rate, Asian',
       'Four-Year Cohort Graduation Rate, Black/African American',
       'Four-Year Cohort Graduation Rate, Economically Disadvantaged',
       'Four-Year Cohort Graduation Rate, English Learners',
       'Four-Year Cohort Graduation Rate, Hispanic/Latino',
       'Four-Year Cohort Graduation Rate, Multiracial',
       'Four-Year Cohort Graduation Rate, Native Hawaiian/Pacific Islander',
       'Four-Year Cohort Graduation Rate, Special Education',
       'Four-Year Cohort Graduation Rate, White',
       'Keystone Algebra I: % of Students Below Basic, Grade 11',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  American Indian/Alaskan Native',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Asian',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Black/African American',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Economically Disadvantaged',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  English Learners',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Hispanic/Latino',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Multiracial',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  Special Education',
       'Keystone Algebra I: % of Students Below Basic, Grade 11,  White',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  American Indian/Alaskan Native',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Asian',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Black/African American',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Economically Disadvantaged',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  English Learners',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Hispanic/Latino',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Multiracial',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  Special Education',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11,  White',
       'Keystone Biology: % of Students Below Basic, Grade 11',
       'Keystone Biology: % of Students Below Basic, Grade 11,  American Indian/Alaskan Native',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Asian',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Black/African American',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Economically Disadvantaged',
       'Keystone Biology: % of Students Below Basic, Grade 11,  English Learners',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Hispanic/Latino',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Multiracial',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Biology: % of Students Below Basic, Grade 11,  Special Education',
       'Keystone Biology: % of Students Below Basic, Grade 11,  White',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  American Indian/Alaskan Native',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Asian',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Black/African American',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Economically Disadvantaged',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  English Learners',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Hispanic/Latino',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Multiracial',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  Special Education',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11,  White',
       'Keystone Literature: % of Students Below Basic, Grade 11',
       'Keystone Literature: % of Students Below Basic, Grade 11,  American Indian/Alaskan Native',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Asian',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Black/African American',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Economically Disadvantaged',
       'Keystone Literature: % of Students Below Basic, Grade 11,  English Learners',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Hispanic/Latino',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Multiracial',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Literature: % of Students Below Basic, Grade 11,  Special Education',
       'Keystone Literature: % of Students Below Basic, Grade 11,  White',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  American Indian/Alaskan Native',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Asian',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Black/African American',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Economically Disadvantaged',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  English Learners',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Hispanic/Latino',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Multiracial',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Native Hawaiian/Pacific Islander',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  Special Education',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11,  White',
       '% of 11th Grade Students Proficient on All Three Keystones',
       '% of 11th Grade Students Proficient on All Three Keystones - American Indian/Alaskan Native',
       '% of 11th Grade Students Proficient on All Three Keystones - Asian',
       '% of 11th Grade Students Proficient on All Three Keystones - Black/African American',
       '% of 11th Grade Students Proficient on All Three Keystones - Economically Disadvantaged',
       '% of 11th Grade Students Proficient on All Three Keystones - English Learner',
       '% of 11th Grade Students Proficient on All Three Keystones - Hispanic/Latino',
       '% of 11th Grade Students Proficient on All Three Keystones - Multiracial',
       '% of 11th Grade Students Proficient on All Three Keystones - Native Hawaiian/Alaskan Native',
       '% of 11th Grade Students Proficient on All Three Keystones - Special Education',
       '% of 11th Grade Students Proficient on All Three Keystones - White',
       '% of 12th Grade CTE Students Meeting Industry Standards',
       'Ninth-Grade On-Track Rate',
       '% of Students Receiving Zero Out-of-School Suspensions',
       'Percent of Metrics Improving,  All Students',
       'Percent of Metrics Improving,  American Indian/Alaskan Native',
       'Percent of Metrics Improving,  Asian',
       'Percent of Metrics Improving,  Black/African American',
       'Percent of Metrics Improving,  Economically Disadvantaged',
       'Percent of Metrics Improving,  English Learners',
       'Percent of Metrics Improving,  Hispanic/Latino',
       'Percent of Metrics Improving,  Multiracial',
       'Percent of Metrics Improving,  Native Hawaiian/Pacific Islander',
       'Percent of Metrics Improving,  Special Education',
       'Percent of Metrics Improving,  White',
       'Percent of Targets Met,  All Students',
       'Percent of Targets Met,  American Indian/Alaskan Native',
       'Percent of Targets Met,  Asian',
       'Percent of Targets Met,  Black/African American',
       'Percent of Targets Met,  Economically Disadvantaged',
       'Percent of Targets Met,  English Learners',
       'Percent of Targets Met,  Hispanic/Latino',
       'Percent of Targets Met,  Multiracial',
       'Percent of Targets Met,  Native Hawaiian/Pacific Islander',
       'Percent of Targets Met,  Special Education',
       'Percent of Targets Met,  White',
       'PSSA ELA: % of Students Below Basic, Grades 3-8',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  American Indian/Alaskan Native',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Asian',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Black/African American',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Economically Disadvantaged',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  English Learners',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Hispanic/Latino',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Multiracial',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Native Hawaiian/Pacific Islander',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  Special Education',
       'PSSA ELA: % of Students Below Basic, Grades 3-8,  White',
       'PSSA ELA: % of Students Below Basic, Grade 3',
       'PSSA ELA: % of Students Below Basic, Grade 3,  American Indian/Alaskan Native',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Asian',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Black/African American',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Economically Disadvantaged',
       'PSSA ELA: % of Students Below Basic, Grade 3,  English Learners',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Hispanic/Latino',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Multiracial',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Native Hawaiian/Pacific Islander',
       'PSSA ELA: % of Students Below Basic, Grade 3,  Special Education',
       'PSSA ELA: % of Students Below Basic, Grade 3,  White',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, American Indian/Alaskan Native',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Asian',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Black/African American',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Economically Disadvantaged',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, English Learners',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Hispanic/Latino',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Multiracial',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Native Hawaiian/Pacific Islander',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, Special Education',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8, White',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, American Indian/Alaskan Native',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Asian',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Black/African American',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Economically Disadvantaged',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, English Learners',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Hispanic/Latino',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Multiracial',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Native Hawaiian/Pacific Islander',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, Special Education',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3, White',
       'PSSA Math: % of Students Below Basic, Grades 3-8',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  American Indian/Alaskan Native',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Asian',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Black/African American',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Economically Disadvantaged',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  English Learners',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Hispanic/Latino',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Multiracial',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Native Hawaiian/Pacific Islander',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  Special Education',
       'PSSA Math: % of Students Below Basic, Grades 3-8,  White',
       'PSSA Math: % of Students Below Basic, Grade 3',
       'PSSA Math: % of Students Below Basic, Grade 3,  American Indian/Alaskan Native',
       'PSSA Math: % of Students Below Basic, Grade 3,  Asian',
       'PSSA Math: % of Students Below Basic, Grade 3,  Black/African American',
       'PSSA Math: % of Students Below Basic, Grade 3,  Economically Disadvantaged',
       'PSSA Math: % of Students Below Basic, Grade 3,  English Learners',
       'PSSA Math: % of Students Below Basic, Grade 3,  Hispanic/Latino',
       'PSSA Math: % of Students Below Basic, Grade 3,  Multiracial',
       'PSSA Math: % of Students Below Basic, Grade 3,  Native Hawaiian/Pacific Islander',
       'PSSA Math: % of Students Below Basic, Grade 3,  Special Education',
       'PSSA Math: % of Students Below Basic, Grade 3,  White',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, American Indian/Alaskan Native',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Asian',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Black/African American',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Economically Disadvantaged',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, English Learners',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Hispanic/Latino',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Multiracial',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Native Hawaiian/Pacific Islander',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, Special Education',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8, White',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  American Indian/Alaskan Native',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Asian',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Black/African American',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Economically Disadvantaged',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  English Learners',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Hispanic/Latino',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Multiracial',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Native Hawaiian/Pacific Islander',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  Special Education',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3,  White',
       'PSSA Science: % of Students Below Basic, Grades 4-8',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  American Indian/Alaskan Native',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Asian',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Black/African American',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Economically Disadvantaged',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  English Learners',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Hispanic/Latino',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Multiracial',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Native Hawaiian/Pacific Islander',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  Special Education',
       'PSSA Science: % of Students Below Basic, Grades 4-8,  White',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  American Indian/Alaskan Native',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Asian',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Black/African American',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Economically Disadvantaged',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  English Learners',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Hispanic/Latino',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Multiracial',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Native Hawaiian/Pacific Islander',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  Special Education',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8,  White',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient',
       '% of Teachers Attending at Least 90% of Instructional Days',
       'Year-to-Year Teacher Retention'], dtype=object)

In [14]:
# Create a list a metrics to keep
high_school_metrics_to_keep = [
       'Admission Type',
       '% of Students Attending at Least 90% of Instructional Days',
       'Number of Dropouts - Last School of Touch (Grades 7-12)',
       '# of Students Served Over the Full Year', 
       'October 1 Enrollment',
       '% of Students Completing the FAFSA by End of 12th Grade',
       'First-Fall Matriculation', 
       'Four-Year Cohort Graduation Rate',
       'Keystone Algebra I: % of Students Below Basic, Grade 11',
       'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11',
       'Keystone Biology: % of Students Below Basic, Grade 11',
       'Keystone Biology: % of Students Proficient or Advanced, Grade 11',
       'Keystone Literature: % of Students Below Basic, Grade 11',
       'Keystone Literature: % of Students Proficient or Advanced, Grade 11',
       '% of 11th Grade Students Proficient on All Three Keystones',
       '% of 12th Grade CTE Students Meeting Industry Standards',
       'Ninth-Grade On-Track Rate',
       '% of Students Receiving Zero Out-of-School Suspensions',
       'Percent of Metrics Improving,  All Students',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient',
       '% of Teachers Attending at Least 90% of Instructional Days',
       'Year-to-Year Teacher Retention'
]
print("Number of metrics to keep:", len(high_school_metrics_to_keep))

Number of metrics to keep: 23

In [15]:
# Reduce the number of rows by keeping only the rows with a 'metric' in high_school_metrics_to_keep
high_school_metrics_df = high_school_metrics_df[high_school_metrics_df['metric'].isin(high_school_metrics_to_keep)]

# Print info for cleaned dataframe
high_school_count = high_school_metrics_df['school_name'].nunique()
print("Number of High Schools:", high_school_count)
high_school_metrics_count = high_school_metrics_df['metric'].nunique()
print("Number of High School metrics:", high_school_metrics_count)
high_school_metrics_df.info()

Number of High Schools: 84
Number of High School metrics: 23
<class 'pandas.core.frame.DataFrame'>
Index: 1932 entries, 0 to 83719
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  1932 non-null   object
 1   school_id            1932 non-null   int64
 2   school_name          1932 non-null   object
 3   report_type          1932 non-null   object
 4   metric               1932 non-null   object
 5   numerator            1398 non-null   float64
 6   denominator          1398 non-null   float64
 7   metric_score         1932 non-null   object
 8   score_previous       1847 non-null   object
 9   score_change         1848 non-null   object
 10  tier                 921 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 181.1+ KB

In [16]:
# Verify the new dataframe has the correct number of metrics

# Create list of high school metrics
high_school_metrics = high_school_metrics_df['metric'].unique()

# Convert the lists to sets
high_school_metrics_set = set(high_school_metrics)
high_school_metrics_to_keep_set = set(high_school_metrics_to_keep)

# Find elements only in high_school_metrics
only_in_high_school_metrics = high_school_metrics_set.difference(high_school_metrics_to_keep_set)

# Find elements only in high_school_metrics_to_keep
only_in_high_school_to_keep_metrics = high_school_metrics_to_keep_set.difference(high_school_metrics_set)

# Print the results
print("Number of high_school_metrics:", len(high_school_metrics_set))
print("Number of high_school_metrics_to_keep:", len(high_school_metrics_to_keep_set))
print("Only in high_school_metrics:", only_in_high_school_metrics)
print("Only in high_school_metrics_to_keep:", only_in_high_school_to_keep_metrics)

Number of high_school_metrics: 23
Number of high_school_metrics_to_keep: 23
Only in high_school_metrics: set()
Only in high_school_metrics_to_keep: set()

In [17]:
middle_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
1300,2022-2023,1130,William T. Tilden School,Middle School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1301,2022-2023,1130,William T. Tilden School,Middle School,% of Students Attending Less Than 80% of Instr...,47.0,404.0,11.6,NaN,NaN,NaN
1302,2022-2023,1130,William T. Tilden School,Middle School,% of Students Attending 80-85% of Instructiona...,22.0,404.0,5.5,NaN,NaN,NaN
1303,2022-2023,1130,William T. Tilden School,Middle School,% of Students Attending 85-90% of Instructiona...,55.0,404.0,13.6,NaN,NaN,NaN
1304,2022-2023,1130,William T. Tilden School,Middle School,% of Students Attending at Least 90% of Instru...,280.0,404.0,69.3,50.5,18.8,Improving

In [18]:
# list all the middle school metrics
ms_unique_metrics = middle_school_metrics_df['metric'].unique()
# ms_unique_metrics

In [19]:
# Create a list a metrics to keep
middle_school_metrics_to_keep = [
       'Admission Type',
       '% of Students Attending at Least 90% of Instructional Days',
       'Number of Dropouts - Last School of Touch (Grades 7-12)',
       '# of Students Served Over the Full Year', 'October 1 Enrollment',
       '% of Students Receiving Zero Out-of-School Suspensions',
       'Percent of Metrics Improving,  All Students',
       'PSSA ELA: % of Students Below Basic, Grades 3-8',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Math: % of Students Below Basic, Grades 3-8',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Science: % of Students Below Basic, Grades 4-8',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient',
       '% of Teachers Attending at Least 90% of Instructional Days',
       'Year-to-Year Teacher Retention'
]

print("Number of metrics to keep:", len(middle_school_metrics_to_keep))

Number of metrics to keep: 17

In [20]:
# Reduce the number of rows by keeping only the rows with a 'metric' in middle_school_metrics_to_keep
middle_school_metrics_df = middle_school_metrics_df[middle_school_metrics_df['metric'].isin(middle_school_metrics_to_keep)]

# Print info for cleaned dataframe
middle_school_count = middle_school_metrics_df['school_name'].nunique()
print("Number of Middle Schools:", middle_school_count)
middle_school_metrics_count = middle_school_metrics_df['metric'].nunique()
print("Number of Middle School metrics:", middle_school_metrics_count)
middle_school_metrics_df.info()

Number of Middle Schools: 29
Number of Middle School metrics: 17
<class 'pandas.core.frame.DataFrame'>
Index: 493 entries, 1300 to 77739
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  493 non-null    object
 1   school_id            493 non-null    int64
 2   school_name          493 non-null    object
 3   report_type          493 non-null    object
 4   metric               493 non-null    object
 5   numerator            338 non-null    float64
 6   denominator          338 non-null    float64
 7   metric_score         493 non-null    object
 8   score_previous       463 non-null    object
 9   score_change         464 non-null    object
 10  tier                 271 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 46.2+ KB

In [21]:
# Verify the new dataframe has the correct number of metrics

# Create list of middle school metrics
middle_school_metrics = middle_school_metrics_df['metric'].unique()

# Convert the lists to sets
middle_school_metrics_set = set(middle_school_metrics)
middle_school_metrics_to_keep_set = set(middle_school_metrics_to_keep)

# Find elements only in middle_school_metrics
only_in_middle_school_metrics = middle_school_metrics_set.difference(middle_school_metrics_to_keep_set)

# Find elements only in middle_school_metrics_to_keep
only_in_middle_school_to_keep_metrics = middle_school_metrics_to_keep_set.difference(middle_school_metrics_set)

# Print the results
print("Number of middle_school_metrics:", len(middle_school_metrics_set))
print("Number of middle_school_metrics_to_keep:", len(middle_school_metrics_to_keep_set))
print("Only in middle_school_metrics:", only_in_middle_school_metrics)
print("Only in middle_school_metrics_to_keep:", only_in_middle_school_to_keep_metrics)

Number of middle_school_metrics: 17
Number of middle_school_metrics_to_keep: 17
Only in middle_school_metrics: set()
Only in middle_school_metrics_to_keep: set()

In [22]:
ktoeight_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
1820,2022-2023,1200,John Barry School,K-8 School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1821,2022-2023,1200,John Barry School,K-8 School,% of Students Attending Less Than 80% of Instr...,205.0,602.0,34.1,NaN,NaN,NaN
1822,2022-2023,1200,John Barry School,K-8 School,% of Students Attending 80-85% of Instructiona...,78.0,602.0,13,NaN,NaN,NaN
1823,2022-2023,1200,John Barry School,K-8 School,% of Students Attending 85-90% of Instructiona...,93.0,602.0,15.5,NaN,NaN,NaN
1824,2022-2023,1200,John Barry School,K-8 School,% of Students Attending at Least 90% of Instru...,226.0,602.0,37.5,27,10.5,Improving

In [23]:
# list all the high school metrics
ktes_unique_metrics = ktoeight_school_metrics_df['metric'].unique()
# ktes_unique_metrics

In [24]:
# Create a list a metrics to keep
ktoeight_school_metrics_to_keep = [
       'Admission Type',
       '% of Students Attending at Least 90% of Instructional Days',
       'Number of Dropouts - Last School of Touch (Grades 7-12)',
       '# of Students Served Over the Full Year', 'October 1 Enrollment',
       '% of Students Receiving Zero Out-of-School Suspensions',
       'Percent of Metrics Improving,  All Students',
       'PSSA ELA: % of Students Below Basic, Grades 3-8',
       'PSSA ELA: % of Students Below Basic, Grade 3',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
       'PSSA Math: % of Students Below Basic, Grades 3-8',
       'PSSA Math: % of Students Below Basic, Grade 3',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3',
       'PSSA Science: % of Students Below Basic, Grades 4-8',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient',
       '% of Teachers Attending at Least 90% of Instructional Days',
       'Year-to-Year Teacher Retention'
]

print("Number of metrics to keep:", len(ktoeight_school_metrics_to_keep))

Number of metrics to keep: 21

In [25]:
# Reduce the number of rows by keeping only the rows with a 'metric' in ktoeight_school_metrics_to_keep
ktoeight_school_metrics_df = ktoeight_school_metrics_df[ktoeight_school_metrics_df['metric'].isin(ktoeight_school_metrics_to_keep)]

# Print info for cleaned dataframe
ktoeight_school_count = ktoeight_school_metrics_df['school_name'].nunique()
print("Number of K-8 Schools:", ktoeight_school_count)
ktoeight_school_metrics_count = ktoeight_school_metrics_df['metric'].nunique()
print("Number of K-8 School metrics:", ktoeight_school_metrics_count)
ktoeight_school_metrics_df.info()

Number of K-8 Schools: 154
Number of K-8 School metrics: 21
<class 'pandas.core.frame.DataFrame'>
Index: 3234 entries, 1820 to 83979
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  3234 non-null   object
 1   school_id            3234 non-null   int64
 2   school_name          3234 non-null   object
 3   report_type          3234 non-null   object
 4   metric               3234 non-null   object
 5   numerator            2379 non-null   float64
 6   denominator          2379 non-null   float64
 7   metric_score         3234 non-null   object
 8   score_previous       3077 non-null   object
 9   score_change         3080 non-null   object
 10  tier                 2053 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 303.2+ KB

In [26]:
# Verify the new dataframe has the correct number of metrics

# Create list of k-8 school metrics
ktoeight_school_metrics = ktoeight_school_metrics_df['metric'].unique()

# Convert the lists to sets
ktoeight_school_metrics_set = set(ktoeight_school_metrics)
ktoeight_school_metrics_to_keep_set = set(ktoeight_school_metrics_to_keep)

# Find elements only in ktoeight_school_metrics
only_in_ktoeight_school_metrics = ktoeight_school_metrics_set.difference(ktoeight_school_metrics_to_keep_set)

# Find elements only in ktoeight_school_metrics_to_keep
only_in_ktoeight_school_to_keep_metrics = ktoeight_school_metrics_to_keep_set.difference(ktoeight_school_metrics_set)

# Print the results
print("Number of ktoeight_school_metrics:", len(ktoeight_school_metrics_set))
print("Number of ktoeight_school_metrics_to_keep:", len(ktoeight_school_metrics_to_keep_set))
print("Only in ktoeight_school_metrics:", only_in_ktoeight_school_metrics)
print("Only in ktoeight_school_metrics_to_keep:", only_in_ktoeight_school_to_keep_metrics)

Number of ktoeight_school_metrics: 21
Number of ktoeight_school_metrics_to_keep: 21
Only in ktoeight_school_metrics: set()
Only in ktoeight_school_metrics_to_keep: set()

In [27]:
elementary_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
2340,2022-2023,1250,Joseph W. Catharine School,Elementary School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
2341,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Attending Less Than 80% of Instr...,60.0,447.0,13.4,NaN,NaN,NaN
2342,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Attending 80-85% of Instructiona...,27.0,447.0,6,NaN,NaN,NaN
2343,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Attending 85-90% of Instructiona...,62.0,447.0,13.9,NaN,NaN,NaN
2344,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Attending at Least 90% of Instru...,298.0,447.0,66.7,56.1,10.6,Improving

In [28]:
# list all the high school metrics
es_unique_metrics = elementary_school_metrics_df['metric'].unique()
# es_unique_metrics

In [29]:
# Create a list a metrics to keep
elementary_school_metrics_to_keep = [
       'Admission Type',
       '% of Students Attending at Least 90% of Instructional Days',
       '# of Students Served Over the Full Year', 'October 1 Enrollment',
       '% of Students Receiving Zero Out-of-School Suspensions',
       'Percent of Metrics Improving,  All Students',
       'PSSA ELA: % of Students Below Basic, Grades 3-8',
       'PSSA ELA: % of Students Below Basic, Grade 3',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
       'PSSA Math: % of Students Below Basic, Grades 3-8',
       'PSSA Math: % of Students Below Basic, Grade 3',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3',
       'PSSA Science: % of Students Below Basic, Grades 4-8',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient',
       '% of Teachers Attending at Least 90% of Instructional Days',
       'Year-to-Year Teacher Retention'
]

print("Number of metrics to keep:", len(elementary_school_metrics_to_keep))

Number of metrics to keep: 20

In [30]:
# Reduce the number of rows by keeping only the rows with a 'metric' in elementary_school_metrics_to_keep
elementary_school_metrics_df = elementary_school_metrics_df[elementary_school_metrics_df['metric'].isin(elementary_school_metrics_to_keep)]

# Print info for cleaned dataframe
elementary_school_count = elementary_school_metrics_df['school_name'].nunique()
print("Number of Elementary Schools:", elementary_school_count)
elementary_school_metrics_count = elementary_school_metrics_df['metric'].nunique()
print("Number of Elementary School metrics:", elementary_school_metrics_count)
elementary_school_metrics_df.info()

Number of Elementary Schools: 56
Number of Elementary School metrics: 20
<class 'pandas.core.frame.DataFrame'>
Index: 1120 entries, 2340 to 82939
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  1120 non-null   object
 1   school_id            1120 non-null   int64
 2   school_name          1120 non-null   object
 3   report_type          1120 non-null   object
 4   metric               1120 non-null   object
 5   numerator            886 non-null    float64
 6   denominator          886 non-null    float64
 7   metric_score         1120 non-null   object
 8   score_previous       1064 non-null   object
 9   score_change         1064 non-null   object
 10  tier                 691 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 105.0+ KB

In [31]:
# Verify the new dataframe has the correct number of metrics

# Create list of elemenarty school metrics
elementary_school_metrics = elementary_school_metrics_df['metric'].unique()

# Convert the lists to sets
elementary_school_metrics_set = set(elementary_school_metrics)
elementary_school_metrics_to_keep_set = set(elementary_school_metrics_to_keep)

# Find elements only in elementary_school_metrics
only_in_elementary_school_metrics = elementary_school_metrics_set.difference(elementary_school_metrics_to_keep_set)

# Find elements only in elementary_school_metrics
only_in_elementary_school_to_keep_metrics = elementary_school_metrics_to_keep_set.difference(elementary_school_metrics_set)

# Print the results
print("Number of elementary_school_metrics:", len(elementary_school_metrics_set))
print("Number of elementary_school_metrics_to_keep:", len(elementary_school_metrics_to_keep_set))
print("Only in elementary_school_metrics:", only_in_elementary_school_metrics)
print("Only in elementary_school_metrics_to_keep:", only_in_elementary_school_to_keep_metrics)

Number of elementary_school_metrics: 20
Number of elementary_school_metrics_to_keep: 20
Only in elementary_school_metrics: set()
Only in elementary_school_metrics_to_keep: set()

In [32]:
# Print info for dataframes with reduced rows
print("Number of High Schools:", high_school_count)
print("Number of High School metrics:", high_school_metrics_count)
high_school_metrics_df.info()
print('-' * 60)
print("Number of Middle Schools:", middle_school_count)
print("Number of Middle School metrics:", middle_school_metrics_count)
middle_school_metrics_df.info()
print('-' * 60)
print("Number of K-8 Schools:", ktoeight_school_count)
print("Number of K-8 School metrics:", ktoeight_school_metrics_count)
ktoeight_school_metrics_df.info()
print('-' * 60)
print("Number of Elementary Schools:", elementary_school_count)
print("Number of Elementary School metrics:", elementary_school_metrics_count)
elementary_school_metrics_df.info()
print('-' * 60)
all_schools = high_school_count + middle_school_count + ktoeight_school_count + elementary_school_count
print("Number of Schools:", all_schools)

Number of High Schools: 84
Number of High School metrics: 23
<class 'pandas.core.frame.DataFrame'>
Index: 1932 entries, 0 to 83719
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  1932 non-null   object
 1   school_id            1932 non-null   int64
 2   school_name          1932 non-null   object
 3   report_type          1932 non-null   object
 4   metric               1932 non-null   object
 5   numerator            1398 non-null   float64
 6   denominator          1398 non-null   float64
 7   metric_score         1932 non-null   object
 8   score_previous       1847 non-null   object
 9   score_change         1848 non-null   object
 10  tier                 921 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 181.1+ KB
------------------------------------------------------------
Number of Middle Schools: 29
Number of Middle School metrics: 17
<class 'pandas.core.frame.DataFrame'>
Index: 493 entries, 1300 to 77739
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  493 non-null    object
 1   school_id            493 non-null    int64
 2   school_name          493 non-null    object
 3   report_type          493 non-null    object
 4   metric               493 non-null    object
 5   numerator            338 non-null    float64
 6   denominator          338 non-null    float64
 7   metric_score         493 non-null    object
 8   score_previous       463 non-null    object
 9   score_change         464 non-null    object
 10  tier                 271 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 46.2+ KB
------------------------------------------------------------
Number of K-8 Schools: 154
Number of K-8 School metrics: 21
<class 'pandas.core.frame.DataFrame'>
Index: 3234 entries, 1820 to 83979
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  3234 non-null   object
 1   school_id            3234 non-null   int64
 2   school_name          3234 non-null   object
 3   report_type          3234 non-null   object
 4   metric               3234 non-null   object
 5   numerator            2379 non-null   float64
 6   denominator          2379 non-null   float64
 7   metric_score         3234 non-null   object
 8   score_previous       3077 non-null   object
 9   score_change         3080 non-null   object
 10  tier                 2053 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 303.2+ KB
------------------------------------------------------------
Number of Elementary Schools: 56
Number of Elementary School metrics: 20
<class 'pandas.core.frame.DataFrame'>
Index: 1120 entries, 2340 to 82939
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accountability_year  1120 non-null   object
 1   school_id            1120 non-null   int64
 2   school_name          1120 non-null   object
 3   report_type          1120 non-null   object
 4   metric               1120 non-null   object
 5   numerator            886 non-null    float64
 6   denominator          886 non-null    float64
 7   metric_score         1120 non-null   object
 8   score_previous       1064 non-null   object
 9   score_change         1064 non-null   object
 10  tier                 691 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 105.0+ KB
------------------------------------------------------------
Number of Schools: 323

In [33]:
high_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
0,2022-2023,1010,John Bartram High School,High School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
4,2022-2023,1010,John Bartram High School,High School,% of Students Attending at Least 90% of Instru...,208.0,617.0,33.7,33.8,-0.1,Maintaining
7,2022-2023,1010,John Bartram High School,High School,Number of Dropouts - Last School of Touch (Gra...,NaN,NaN,41,54,-13,Improving
8,2022-2023,1010,John Bartram High School,High School,# of Students Served Over the Full Year,NaN,NaN,617,642,-25,NaN
9,2022-2023,1010,John Bartram High School,High School,October 1 Enrollment,NaN,NaN,478,489,-11,NaN

In [34]:
# Pivot the high_school_metrics_df DataFrame to create one row for each school 
hs_metrics_df = high_school_metrics_df.pivot_table(
    index = ['accountability_year', 'school_id', 'school_name', 'report_type'],
    columns = 'metric', 
    values = 'metric_score',
    aggfunc='first'
).reset_index()

hs_metrics_df.head()

metric,accountability_year,school_id,school_name,report_type,# of Students Served Over the Full Year,% of 11th Grade Students Proficient on All Three Keystones,% of 12th Grade CTE Students Meeting Industry Standards,% of Students Attending at Least 90% of Instructional Days,% of Students Completing the FAFSA by End of 12th Grade,% of Students Receiving Zero Out-of-School Suspensions,...,"Keystone Algebra I: % of Students Proficient or Advanced, Grade 11","Keystone Biology: % of Students Below Basic, Grade 11","Keystone Biology: % of Students Proficient or Advanced, Grade 11","Keystone Literature: % of Students Below Basic, Grade 11","Keystone Literature: % of Students Proficient or Advanced, Grade 11",Ninth-Grade On-Track Rate,Number of Dropouts - Last School of Touch (Grades 7-12),October 1 Enrollment,"Percent of Metrics Improving, All Students",Year-to-Year Teacher Retention
0,2022-2023,1010,John Bartram High School,High School,617,4.2,Insufficient Sample,33.7,30.7,80.6,...,7.3,61.2,17.9,56.3,17.2,71.1,41,478,58.3,73.2
1,2022-2023,1020,West Philadelphia High School,High School,608,0,20,30.3,30.5,94.6,...,9.8,63.8,10.3,35.6,17,76.1,34,545,38.5,79.6
2,2022-2023,1030,High School of the Future,High School,578,4.8,Insufficient Sample,43.4,44.9,90.7,...,5.6,58.1,8.6,20.9,30.4,62.9,20,569,58.3,72.9
3,2022-2023,1050,Paul Robeson High School for Human Services,High School,341,15.8,Insufficient Sample,67.7,61.2,99.4,...,18.4,34.7,24,5.3,53.3,72.4,9,313,50,90
4,2022-2023,1100,William L. Sayre High School,High School,474,1.7,Insufficient Sample,36.7,19.3,81.2,...,3.7,69.6,1.8,40,16.4,87.7,27,355,33.3,86.1

In [35]:
# List the hs_metrics_df columns
# hs_metrics_df.columns

In [36]:
# Create a list with desireds column order
hs_columns = [
    'accountability_year', 
    'school_id', 
    'school_name', 
    'report_type', 
    'Admission Type', 
    '# of Students Served Over the Full Year', 
    'October 1 Enrollment', 
    '% of 11th Grade Students Proficient on All Three Keystones', 
    'Keystone Algebra I: % of Students Below Basic, Grade 11', 
    'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11', 
    'Keystone Biology: % of Students Below Basic, Grade 11', 
    'Keystone Biology: % of Students Proficient or Advanced, Grade 11', 
    'Keystone Literature: % of Students Below Basic, Grade 11', 
    'Keystone Literature: % of Students Proficient or Advanced, Grade 11', 
    '% of 12th Grade CTE Students Meeting Industry Standards', 
    'Ninth-Grade On-Track Rate', 
    'Percent of Metrics Improving,  All Students', 
    '% of Students Attending at Least 90% of Instructional Days', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)', 
    '% of Students Receiving Zero Out-of-School Suspensions', 
    '% of Students Completing the FAFSA by End of 12th Grade',
    'First-Fall Matriculation',
    'Four-Year Cohort Graduation Rate'
]
# Reorder the DataFrame columns
hs_metrics_df = hs_metrics_df[hs_columns]

In [37]:
# Rename the Columns with compatible formatting 
hs_metrics_df = hs_metrics_df.rename(columns={
    'accountability_year': 'Year', 
    'school_id': 'school_id', 
    'school_name': 'School_Name', 
    'report_type': 'Report_Type', 
    'Admission Type': 'Admission_Type', 
    '# of Students Served Over the Full Year': 'Number_Students_Served_Full_Year', 
    'October 1 Enrollment': 'October_1_Enrollment', 
    '% of 11th Grade Students Proficient on All Three Keystones': 'Percent_11th_Grade_Students_Proficient_All_Three_Keystones', 
    'Keystone Algebra I: % of Students Below Basic, Grade 11': 'Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I', 
    'Keystone Algebra I: % of Students Proficient or Advanced, Grade 11': 'Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I', 
    'Keystone Biology: % of Students Below Basic, Grade 11': 'Percent_11th_Grade_Students_Below_Basic_Keystone_Biology', 
    'Keystone Biology: % of Students Proficient or Advanced, Grade 11': 'Percent_11th_Grade_Students_Proficient_Keystone_Biology', 
    'Keystone Literature: % of Students Below Basic, Grade 11': 'Percent_11th_Grade_Students_Below_Basic_Keystone_Literature', 
    'Keystone Literature: % of Students Proficient or Advanced, Grade 11': 'Percent_11th_Grade_Students_Proficient_Keystone_Literature', 
    '% of 12th Grade CTE Students Meeting Industry Standards': 'Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards', 
    'Ninth-Grade On-Track Rate': 'Ninth_Grade_On_Track_Rate', 
    'Percent of Metrics Improving,  All Students': 'Percent_Metrics_Improving_All_Students', 
    '% of Students Attending at Least 90% of Instructional Days': 'Percent_Students_Attending_at_Least_90_Percent', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)': 'Number_Dropouts_Grades_7_to_12', 
    '% of Students Receiving Zero Out-of-School Suspensions': 'Percent_Students_Receiving_Zero_Out_of_School_Suspensions', 
    '% of Students Completing the FAFSA by End of 12th Grade': 'Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade',
    'First-Fall Matriculation': 'First_Fall_Matriculation',
    'Four-Year Cohort Graduation Rate': 'Four_Year_Cohort_Graduation_Rate'
})

hs_metrics_df.head()

metric,Year,school_id,School_Name,Report_Type,Admission_Type,Number_Students_Served_Full_Year,October_1_Enrollment,Percent_11th_Grade_Students_Proficient_All_Three_Keystones,Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I,Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I,...,Percent_11th_Grade_Students_Proficient_Keystone_Literature,Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards,Ninth_Grade_On_Track_Rate,Percent_Metrics_Improving_All_Students,Percent_Students_Attending_at_Least_90_Percent,Number_Dropouts_Grades_7_to_12,Percent_Students_Receiving_Zero_Out_of_School_Suspensions,Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade,First_Fall_Matriculation,Four_Year_Cohort_Graduation_Rate
0,2022-2023,1010,John Bartram High School,High School,Catchment,617,478,4.2,62.3,7.3,...,17.2,Insufficient Sample,71.1,58.3,33.7,41,80.6,30.7,24.2,70.5
1,2022-2023,1020,West Philadelphia High School,High School,Catchment,608,545,0,54.1,9.8,...,17,20,76.1,38.5,30.3,34,94.6,30.5,41.5,82.1
2,2022-2023,1030,High School of the Future,High School,Citywide,578,569,4.8,46.4,5.6,...,30.4,Insufficient Sample,62.9,58.3,43.4,20,90.7,44.9,22.7,92.4
3,2022-2023,1050,Paul Robeson High School for Human Services,High School,Citywide,341,313,15.8,21.1,18.4,...,53.3,Insufficient Sample,72.4,50,67.7,9,99.4,61.2,47.2,96
4,2022-2023,1100,William L. Sayre High School,High School,Catchment,474,355,1.7,72.2,3.7,...,16.4,Insufficient Sample,87.7,33.3,36.7,27,81.2,19.3,31.8,63

In [38]:
hs_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Year                                                         84 non-null     object
 1   school_id                                                    84 non-null     int64
 2   School_Name                                                  84 non-null     object
 3   Report_Type                                                  84 non-null     object
 4   Admission_Type                                               84 non-null     object
 5   Number_Students_Served_Full_Year                             84 non-null     object
 6   October_1_Enrollment                                         84 non-null     object
 7   Percent_11th_Grade_Students_Proficient_All_Three_Keystones   84 non-null     object
 8   Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I   84 non-null     object
 9   Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I    84 non-null     object
 10  Percent_11th_Grade_Students_Below_Basic_Keystone_Biology     84 non-null     object
 11  Percent_11th_Grade_Students_Proficient_Keystone_Biology      84 non-null     object
 12  Percent_11th_Grade_Students_Below_Basic_Keystone_Literature  84 non-null     object
 13  Percent_11th_Grade_Students_Proficient_Keystone_Literature   84 non-null     object
 14  Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards   84 non-null     object
 15  Ninth_Grade_On_Track_Rate                                    84 non-null     object
 16  Percent_Metrics_Improving_All_Students                       84 non-null     object
 17  Percent_Students_Attending_at_Least_90_Percent               84 non-null     object
 18  Number_Dropouts_Grades_7_to_12                               84 non-null     object
 19  Percent_Students_Receiving_Zero_Out_of_School_Suspensions    84 non-null     object
 20  Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade   84 non-null     object
 21  First_Fall_Matriculation                                     84 non-null     object
 22  Four_Year_Cohort_Graduation_Rate                             84 non-null     object
dtypes: int64(1), object(22)
memory usage: 15.2+ KB

In [39]:
# List the hs_metrics_df columns
# hs_metrics_df.columns

In [40]:
# List of columns to convert
hs_columns_to_convert = [
    'Number_Students_Served_Full_Year', 
    'October_1_Enrollment',
    'Percent_11th_Grade_Students_Proficient_All_Three_Keystones',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I',
    'Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Biology',
    'Percent_11th_Grade_Students_Proficient_Keystone_Biology',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Literature',
    'Percent_11th_Grade_Students_Proficient_Keystone_Literature',
    'Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards',
    'Ninth_Grade_On_Track_Rate', 
    'Percent_Metrics_Improving_All_Students',
    'Percent_Students_Attending_at_Least_90_Percent',
    'Number_Dropouts_Grades_7_to_12',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions',
    'Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade',
    'First_Fall_Matriculation', 
    'Four_Year_Cohort_Graduation_Rate'
]

# Apply pd.to_numeric to convert strings to 'NaN'
hs_metrics_df[hs_columns_to_convert] = hs_metrics_df[hs_columns_to_convert].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# Set the datatypes
hs_metrics_df = hs_metrics_df.astype({    
    'Number_Students_Served_Full_Year': 'int64', 
    'October_1_Enrollment': 'int64',
    'Percent_11th_Grade_Students_Proficient_All_Three_Keystones': 'float64',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I': 'float64',
    'Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I': 'float64',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Biology': 'float64',
    'Percent_11th_Grade_Students_Proficient_Keystone_Biology': 'float64',
    'Percent_11th_Grade_Students_Below_Basic_Keystone_Literature': 'float64',
    'Percent_11th_Grade_Students_Proficient_Keystone_Literature': 'float64',
    'Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards': 'float64',
    'Ninth_Grade_On_Track_Rate': 'float64', 
    'Percent_Metrics_Improving_All_Students': 'float64',
    'Percent_Students_Attending_at_Least_90_Percent': 'float64',
    'Number_Dropouts_Grades_7_to_12': 'int64',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions': 'float64',
    'Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade': 'float64',
    'First_Fall_Matriculation': 'float64', 
    'Four_Year_Cohort_Graduation_Rate': 'float64'
})

In [41]:
hs_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Year                                                         84 non-null     object
 1   school_id                                                    84 non-null     int64
 2   School_Name                                                  84 non-null     object
 3   Report_Type                                                  84 non-null     object
 4   Admission_Type                                               84 non-null     object
 5   Number_Students_Served_Full_Year                             84 non-null     int64
 6   October_1_Enrollment                                         84 non-null     int64
 7   Percent_11th_Grade_Students_Proficient_All_Three_Keystones   84 non-null     float64
 8   Percent_11th_Grade_Students_Below_Basic_Keystone_Algebra_I   83 non-null     float64
 9   Percent_11th_Grade_Students_Proficient_Keystone_Algebra_I    83 non-null     float64
 10  Percent_11th_Grade_Students_Below_Basic_Keystone_Biology     82 non-null     float64
 11  Percent_11th_Grade_Students_Proficient_Keystone_Biology      82 non-null     float64
 12  Percent_11th_Grade_Students_Below_Basic_Keystone_Literature  84 non-null     float64
 13  Percent_11th_Grade_Students_Proficient_Keystone_Literature   84 non-null     float64
 14  Percent_12th_Grade_CTE_Students_Meeting_Industry_Standards   21 non-null     float64
 15  Ninth_Grade_On_Track_Rate                                    83 non-null     float64
 16  Percent_Metrics_Improving_All_Students                       81 non-null     float64
 17  Percent_Students_Attending_at_Least_90_Percent               84 non-null     float64
 18  Number_Dropouts_Grades_7_to_12                               84 non-null     int64
 19  Percent_Students_Receiving_Zero_Out_of_School_Suspensions    84 non-null     float64
 20  Percent_Students_Completing_the_FAFSA_by_End_of_12th_Grade   84 non-null     float64
 21  First_Fall_Matriculation                                     82 non-null     float64
 22  Four_Year_Cohort_Graduation_Rate                             84 non-null     float64
dtypes: float64(15), int64(4), object(4)
memory usage: 15.2+ KB

In [42]:
# Export to csv 
hs_metrics_df.to_csv('Outputs_School_Metrics/high_school_metric_scores.csv', index=False)

In [43]:
middle_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
1300,2022-2023,1130,William T. Tilden School,Middle School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1304,2022-2023,1130,William T. Tilden School,Middle School,% of Students Attending at Least 90% of Instru...,280.0,404.0,69.3,50.5,18.8,Improving
1307,2022-2023,1130,William T. Tilden School,Middle School,Number of Dropouts - Last School of Touch (Gra...,NaN,NaN,4,3,1,Not Improving
1308,2022-2023,1130,William T. Tilden School,Middle School,# of Students Served Over the Full Year,NaN,NaN,404,438,-34,NaN
1309,2022-2023,1130,William T. Tilden School,Middle School,October 1 Enrollment,NaN,NaN,329,346,-17,NaN

In [44]:
# Pivot the middle_school_metrics_df DataFrame to create one row for each school 
ms_metrics_df = middle_school_metrics_df.pivot_table(
    index = ['accountability_year', 'school_id', 'school_name', 'report_type'],
    columns = 'metric', 
    values = 'metric_score',
    aggfunc='first'
).reset_index()

ms_metrics_df.head()

metric,accountability_year,school_id,school_name,report_type,# of Students Served Over the Full Year,% of Students Attending at Least 90% of Instructional Days,% of Students Receiving Zero Out-of-School Suspensions,% of Teachers Attending at Least 90% of Instructional Days,% of Teachers Rated as Distinguished,% of Teachers Rated as Proficient,...,Number of Dropouts - Last School of Touch (Grades 7-12),October 1 Enrollment,"PSSA ELA: % of Students Below Basic, Grades 3-8","PSSA ELA: % of Students Proficient or Advanced, Grades 3-8","PSSA Math: % of Students Below Basic, Grades 3-8","PSSA Math: % of Students Proficient or Advanced, Grades 3-8","PSSA Science: % of Students Below Basic, Grades 4-8","PSSA Science: % of Students Proficient or Advanced, Grades 4-8","Percent of Metrics Improving, All Students",Year-to-Year Teacher Retention
0,2022-2023,1130,William T. Tilden School,Middle School,404,69.3,92.6,71,0,100,...,4,329,39.2,16.5,85.6,3.5,63.6,16.2,50,62.1
1,2022-2023,1580,Middle Years Alternative School,Middle School,179,74.3,91.1,93.3,20,80,...,2,171,12.1,38,55.2,14.6,29,41.9,60,75
2,2022-2023,2050,Science Leadership Academy Middle School,Middle School,379,95,95.8,95,0,94.1,...,1,358,12.3,56,55.6,21,35.4,48.1,60,80
3,2022-2023,2140,Julia R. Masterman School,Middle School,735,94.8,97.6,86.4,70.8,29.2,...,1,716,0.6,94,5.6,81.9,0,98.9,20,83.1
4,2022-2023,2410,Girard Academic Music Program,Middle School,332,95.5,96.1,87.9,36,64,...,2,330,0.9,92.2,6.9,72.9,2.4,90.6,50,94.1

In [45]:
# List the ms_metrics_df columns
# ms_metrics_df.columns

In [46]:
# Create a list with desireds column order
ms_columns = [
    'accountability_year', 
    'school_id', 
    'school_name', 
    'report_type', 
    'Admission Type', 
    '# of Students Served Over the Full Year', 
    'October 1 Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grades 3-8',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Math: % of Students Below Basic, Grades 3-8',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Science: % of Students Below Basic, Grades 4-8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
    'Percent of Metrics Improving,  All Students', 
    '% of Students Attending at Least 90% of Instructional Days', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)',
    '% of Students Receiving Zero Out-of-School Suspensions'
]

# Reorder the DataFrame columns
ms_metrics_df = ms_metrics_df[ms_columns]

In [47]:
# Rename the Columns with compatible formatting 
ms_metrics_df = ms_metrics_df.rename(columns={
    'accountability_year': 'Year', 
    'school_id': 'school_id', 
    'school_name': 'School_Name', 
    'report_type': 'Report_Type', 
    'Admission Type': 'Admission_Type', 
    '# of Students Served Over the Full Year': 'Number_Students_Served_Full_Year', 
    'October 1 Enrollment': 'October_1_Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grades 3-8': 'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Math: % of Students Below Basic, Grades 3-8': 'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Science: % of Students Below Basic, Grades 4-8': 'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8': 'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent of Metrics Improving,  All Students': 'Percent_Metrics_Improving_All_Students', 
    '% of Students Attending at Least 90% of Instructional Days': 'Percent_Students_Attending_at_Least_90_Percent', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)': 'Number_Dropouts_Grades_7_to_12',
    '% of Students Receiving Zero Out-of-School Suspensions': 'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
})
ms_metrics_df.head()

metric,Year,school_id,School_Name,Report_Type,Admission_Type,Number_Students_Served_Full_Year,October_1_Enrollment,PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8,PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8,PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8,PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8,Percent_Metrics_Improving_All_Students,Percent_Students_Attending_at_Least_90_Percent,Number_Dropouts_Grades_7_to_12,Percent_Students_Receiving_Zero_Out_of_School_Suspensions
0,2022-2023,1130,William T. Tilden School,Middle School,Catchment,404,329,39.2,16.5,85.6,3.5,63.6,16.2,50,69.3,4,92.6
1,2022-2023,1580,Middle Years Alternative School,Middle School,Citywide,179,171,12.1,38,55.2,14.6,29,41.9,60,74.3,2,91.1
2,2022-2023,2050,Science Leadership Academy Middle School,Middle School,Catchment,379,358,12.3,56,55.6,21,35.4,48.1,60,95,1,95.8
3,2022-2023,2140,Julia R. Masterman School,Middle School,Criteria-Based,735,716,0.6,94,5.6,81.9,0,98.9,20,94.8,1,97.6
4,2022-2023,2410,Girard Academic Music Program,Middle School,Criteria-Based,332,330,0.9,92.2,6.9,72.9,2.4,90.6,50,95.5,2,96.1

In [48]:
ms_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                29 non-null     object
 1   school_id                                                           29 non-null     int64
 2   School_Name                                                         29 non-null     object
 3   Report_Type                                                         29 non-null     object
 4   Admission_Type                                                      29 non-null     object
 5   Number_Students_Served_Full_Year                                    29 non-null     object
 6   October_1_Enrollment                                                29 non-null     object
 7   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 29 non-null     object
 8   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      29 non-null     object
 9   PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                29 non-null     object
 10  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     29 non-null     object
 11  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             29 non-null     object
 12  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  29 non-null     object
 13  Percent_Metrics_Improving_All_Students                              29 non-null     object
 14  Percent_Students_Attending_at_Least_90_Percent                      29 non-null     object
 15  Number_Dropouts_Grades_7_to_12                                      29 non-null     object
 16  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           29 non-null     object
dtypes: int64(1), object(16)
memory usage: 4.0+ KB

In [49]:
# List the ms_metrics_df columns
# ms_metrics_df.columns

In [50]:
# List of columns to convert
ms_columns_to_convert = [
    'Number_Students_Served_Full_Year', 
    'October_1_Enrollment',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent_Metrics_Improving_All_Students',
    'Percent_Students_Attending_at_Least_90_Percent',
    'Number_Dropouts_Grades_7_to_12',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
]

# Apply pd.to_numeric to convert strings to 'NaN'
ms_metrics_df[ms_columns_to_convert] = ms_metrics_df[ms_columns_to_convert].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# Set the datatypes
ms_metrics_df = ms_metrics_df.astype({    
    'Number_Students_Served_Full_Year': 'int64', 
    'October_1_Enrollment': 'int64',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8': 'float64',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8': 'float64',
    'Percent_Metrics_Improving_All_Students': 'float64',
    'Percent_Students_Attending_at_Least_90_Percent': 'float64',
    'Number_Dropouts_Grades_7_to_12': 'int64',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions': 'float64'
})

In [51]:
ms_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                29 non-null     object
 1   school_id                                                           29 non-null     int64
 2   School_Name                                                         29 non-null     object
 3   Report_Type                                                         29 non-null     object
 4   Admission_Type                                                      29 non-null     object
 5   Number_Students_Served_Full_Year                                    29 non-null     int64
 6   October_1_Enrollment                                                29 non-null     int64
 7   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 29 non-null     float64
 8   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      29 non-null     float64
 9   PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                29 non-null     float64
 10  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     29 non-null     float64
 11  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             29 non-null     float64
 12  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  29 non-null     float64
 13  Percent_Metrics_Improving_All_Students                              28 non-null     float64
 14  Percent_Students_Attending_at_Least_90_Percent                      29 non-null     float64
 15  Number_Dropouts_Grades_7_to_12                                      29 non-null     int64
 16  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           29 non-null     float64
dtypes: float64(9), int64(4), object(4)
memory usage: 4.0+ KB

In [52]:
# Export to csv 
ms_metrics_df.to_csv('Outputs_School_Metrics/middle_school_metric_scores.csv', index=False)

In [53]:
ktoeight_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
1820,2022-2023,1200,John Barry School,K-8 School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
1824,2022-2023,1200,John Barry School,K-8 School,% of Students Attending at Least 90% of Instru...,226.0,602.0,37.5,27,10.5,Improving
1827,2022-2023,1200,John Barry School,K-8 School,Number of Dropouts - Last School of Touch (Gra...,NaN,NaN,3,11,-8,Improving
1828,2022-2023,1200,John Barry School,K-8 School,# of Students Served Over the Full Year,NaN,NaN,602,549,53,NaN
1829,2022-2023,1200,John Barry School,K-8 School,October 1 Enrollment,NaN,NaN,500,475,25,NaN

In [54]:
# Pivot the ktoeight_school_metrics_df DataFrame to create one row for each school 
ktes_metrics_df = ktoeight_school_metrics_df.pivot_table(
    index = ['accountability_year', 'school_id', 'school_name', 'report_type'],
    columns = 'metric', 
    values = 'metric_score',
    aggfunc='first'
).reset_index()

ktes_metrics_df.head()

metric,accountability_year,school_id,school_name,report_type,# of Students Served Over the Full Year,% of Students Attending at Least 90% of Instructional Days,% of Students Receiving Zero Out-of-School Suspensions,% of Teachers Attending at Least 90% of Instructional Days,% of Teachers Rated as Distinguished,% of Teachers Rated as Proficient,...,"PSSA ELA: % of Students Proficient or Advanced, Grade 3","PSSA ELA: % of Students Proficient or Advanced, Grades 3-8","PSSA Math: % of Students Below Basic, Grade 3","PSSA Math: % of Students Below Basic, Grades 3-8","PSSA Math: % of Students Proficient or Advanced, Grade 3","PSSA Math: % of Students Proficient or Advanced, Grades 3-8","PSSA Science: % of Students Below Basic, Grades 4-8","PSSA Science: % of Students Proficient or Advanced, Grades 4-8","Percent of Metrics Improving, All Students",Year-to-Year Teacher Retention
0,2022-2023,1200,John Barry School,K-8 School,602,37.5,96.8,71.4,14.3,78.6,...,10,14,79.1,81.4,4.7,4.1,42.9,21.4,64.3,79
1,2022-2023,1230,William C. Bryant School,K-8 School,407,44.2,91.4,71,7.7,92.3,...,21.2,16.6,61.3,74.2,6.5,2.2,50,20,85.7,33.3
2,2022-2023,1260,Benjamin B. Comegys School,K-8 School,365,33.7,85.2,55.6,0,87.5,...,13.3,16.8,62.1,76.7,10.3,5.2,38.2,25.5,57.1,60.7
3,2022-2023,1280,Sadie Alexander School,K-8 School,586,96.6,100,92.7,73.7,26.3,...,83.3,85.4,6.9,8.9,81.9,77.1,6.7,89.2,57.1,90
4,2022-2023,1290,Andrew Hamilton School,K-8 School,406,45.1,94.8,86.7,0,76,...,14.8,16.9,77.8,78.8,7.4,3.3,36.1,30.2,85.7,83.9

In [55]:
# List the ktes_metrics_df columns
ktes_metrics_df.columns

Index(['accountability_year', 'school_id', 'school_name', 'report_type',
       '# of Students Served Over the Full Year',
       '% of Students Attending at Least 90% of Instructional Days',
       '% of Students Receiving Zero Out-of-School Suspensions',
       '% of Teachers Attending at Least 90% of Instructional Days',
       '% of Teachers Rated as Distinguished',
       '% of Teachers Rated as Proficient', 'Admission Type',
       'Number of Dropouts - Last School of Touch (Grades 7-12)',
       'October 1 Enrollment', 'PSSA ELA: % of Students Below Basic, Grade 3',
       'PSSA ELA: % of Students Below Basic, Grades 3-8',
       'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
       'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Math: % of Students Below Basic, Grade 3',
       'PSSA Math: % of Students Below Basic, Grades 3-8',
       'PSSA Math: % of Students Proficient or Advanced, Grade 3',
       'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
       'PSSA Science: % of Students Below Basic, Grades 4-8',
       'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
       'Percent of Metrics Improving,  All Students',
       'Year-to-Year Teacher Retention'],
      dtype='object', name='metric')

In [56]:
# Create a list with desireds column order
ktes_columns = [
    'accountability_year', 
    'school_id', 
    'school_name', 
    'report_type', 
    'Admission Type', 
    '# of Students Served Over the Full Year', 
    'October 1 Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grade 3',
    'PSSA ELA: % of Students Below Basic, Grades 3-8',
    'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Math: % of Students Below Basic, Grade 3',
    'PSSA Math: % of Students Below Basic, Grades 3-8',
    'PSSA Math: % of Students Proficient or Advanced, Grade 3',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Science: % of Students Below Basic, Grades 4-8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
    'Percent of Metrics Improving,  All Students', 
    '% of Students Attending at Least 90% of Instructional Days', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)',
    '% of Students Receiving Zero Out-of-School Suspensions'
]
# Reorder the DataFrame columns
ktes_metrics_df = ktes_metrics_df[ktes_columns]

In [57]:
# Rename the Columns with compatible formatting 
ktes_metrics_df = ktes_metrics_df.rename(columns={
    'accountability_year': 'Year', 
    'school_id': 'school_id', 
    'school_name': 'School_Name', 
    'report_type': 'Report_Type', 
    'Admission Type': 'Admission_Type', 
    '# of Students Served Over the Full Year': 'Number_Students_Served_Full_Year', 
    'October 1 Enrollment': 'October_1_Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grade 3': 'PSSA_ELA_Percent_Students_Below_Basic_Grade_3',
    'PSSA ELA: % of Students Below Basic, Grades 3-8': 'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA ELA: % of Students Proficient or Advanced, Grade 3': 'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Math: % of Students Below Basic, Grade 3': 'PSSA_Math_Percent_Students_Below_Basic_Grade_3',
    'PSSA Math: % of Students Below Basic, Grades 3-8': 'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA Math: % of Students Proficient or Advanced, Grade 3': 'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Science: % of Students Below Basic, Grades 4-8': 'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8': 'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent of Metrics Improving,  All Students': 'Percent_Metrics_Improving_All_Students', 
    '% of Students Attending at Least 90% of Instructional Days': 'Percent_Students_Attending_at_Least_90_Percent', 
    'Number of Dropouts - Last School of Touch (Grades 7-12)': 'Number_Dropouts_Grades_7_to_12',
    '% of Students Receiving Zero Out-of-School Suspensions': 'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
})

ktes_metrics_df.head()

metric,Year,school_id,School_Name,Report_Type,Admission_Type,Number_Students_Served_Full_Year,October_1_Enrollment,PSSA_ELA_Percent_Students_Below_Basic_Grade_3,PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3,...,PSSA_Math_Percent_Students_Below_Basic_Grade_3,PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3,PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8,PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8,PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8,Percent_Metrics_Improving_All_Students,Percent_Students_Attending_at_Least_90_Percent,Number_Dropouts_Grades_7_to_12,Percent_Students_Receiving_Zero_Out_of_School_Suspensions
0,2022-2023,1200,John Barry School,K-8 School,Catchment,602,500,58,43.5,10,...,79.1,81.4,4.7,4.1,42.9,21.4,64.3,37.5,3,96.8
1,2022-2023,1230,William C. Bryant School,K-8 School,Catchment,407,329,27.3,28.7,21.2,...,61.3,74.2,6.5,2.2,50,20,85.7,44.2,3,91.4
2,2022-2023,1260,Benjamin B. Comegys School,K-8 School,Catchment,365,319,30,28.9,13.3,...,62.1,76.7,10.3,5.2,38.2,25.5,57.1,33.7,1,85.2
3,2022-2023,1280,Sadie Alexander School,K-8 School,Catchment,586,578,5.6,2.9,83.3,...,6.9,8.9,81.9,77.1,6.7,89.2,57.1,96.6,0,100
4,2022-2023,1290,Andrew Hamilton School,K-8 School,Catchment,406,347,33.3,33.8,14.8,...,77.8,78.8,7.4,3.3,36.1,30.2,85.7,45.1,0,94.8

In [58]:
ktes_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 21 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                154 non-null    object
 1   school_id                                                           154 non-null    int64
 2   School_Name                                                         154 non-null    object
 3   Report_Type                                                         154 non-null    object
 4   Admission_Type                                                      154 non-null    object
 5   Number_Students_Served_Full_Year                                    154 non-null    object
 6   October_1_Enrollment                                                154 non-null    object
 7   PSSA_ELA_Percent_Students_Below_Basic_Grade_3                       154 non-null    object
 8   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 154 non-null    object
 9   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3            154 non-null    object
 10  PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      154 non-null    object
 11  PSSA_Math_Percent_Students_Below_Basic_Grade_3                      154 non-null    object
 12  PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                154 non-null    object
 13  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3           154 non-null    object
 14  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     154 non-null    object
 15  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             154 non-null    object
 16  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  154 non-null    object
 17  Percent_Metrics_Improving_All_Students                              154 non-null    object
 18  Percent_Students_Attending_at_Least_90_Percent                      154 non-null    object
 19  Number_Dropouts_Grades_7_to_12                                      154 non-null    object
 20  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           154 non-null    object
dtypes: int64(1), object(20)
memory usage: 25.4+ KB

In [59]:
# List the ms_metrics_df columns
# ktes_metrics_df.columns

In [60]:
# List of columns to convert
ktes_columns_to_convert = [
    'Number_Students_Served_Full_Year', 
    'October_1_Enrollment',
    'PSSA_ELA_Percent_Students_Below_Basic_Grade_3',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Below_Basic_Grade_3',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent_Metrics_Improving_All_Students',
    'Percent_Students_Attending_at_Least_90_Percent',
    'Number_Dropouts_Grades_7_to_12',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
]

# Apply pd.to_numeric to convert strings to 'NaN'
ktes_metrics_df[ktes_columns_to_convert] = ktes_metrics_df[ktes_columns_to_convert].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# Fill NaN values with a placeholder 0 before converting to integers
ktes_metrics_df.fillna({
    'Number_Students_Served_Full_Year': 0,
    'October_1_Enrollment': 0,
    'Number_Dropouts_Grades_7_to_12': 0,
}, inplace=True)

# Set the datatypes
ktes_metrics_df = ktes_metrics_df.astype({    
    'Number_Students_Served_Full_Year': 'int64', 
    'October_1_Enrollment': 'int64',
    'PSSA_ELA_Percent_Students_Below_Basic_Grade_3': 'float64',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3': 'float64',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Below_Basic_Grade_3': 'float64',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3': 'float64',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8': 'float64',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8': 'float64',
    'Percent_Metrics_Improving_All_Students': 'float64',
    'Percent_Students_Attending_at_Least_90_Percent': 'float64',
    'Number_Dropouts_Grades_7_to_12': 'int64',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions': 'float64'
})

In [61]:
ktes_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 21 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                154 non-null    object
 1   school_id                                                           154 non-null    int64
 2   School_Name                                                         154 non-null    object
 3   Report_Type                                                         154 non-null    object
 4   Admission_Type                                                      154 non-null    object
 5   Number_Students_Served_Full_Year                                    154 non-null    int64
 6   October_1_Enrollment                                                154 non-null    int64
 7   PSSA_ELA_Percent_Students_Below_Basic_Grade_3                       146 non-null    float64
 8   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 154 non-null    float64
 9   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3            146 non-null    float64
 10  PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      154 non-null    float64
 11  PSSA_Math_Percent_Students_Below_Basic_Grade_3                      147 non-null    float64
 12  PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                154 non-null    float64
 13  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3           147 non-null    float64
 14  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     154 non-null    float64
 15  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             153 non-null    float64
 16  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  153 non-null    float64
 17  Percent_Metrics_Improving_All_Students                              154 non-null    float64
 18  Percent_Students_Attending_at_Least_90_Percent                      152 non-null    float64
 19  Number_Dropouts_Grades_7_to_12                                      154 non-null    int64
 20  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           152 non-null    float64
dtypes: float64(13), int64(4), object(4)
memory usage: 25.4+ KB

In [62]:
# Export to csv 
ktes_metrics_df.to_csv('Outputs_School_Metrics/ktoeight_school_metric_scores.csv', index=False)

In [63]:
elementary_school_metrics_df.head()

,accountability_year,school_id,school_name,report_type,metric,numerator,denominator,metric_score,score_previous,score_change,tier
2340,2022-2023,1250,Joseph W. Catharine School,Elementary School,Admission Type,NaN,NaN,Catchment,Neighborhood,Not Applicable,NaN
2344,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Attending at Least 90% of Instru...,298.0,447.0,66.7,56.1,10.6,Improving
2348,2022-2023,1250,Joseph W. Catharine School,Elementary School,# of Students Served Over the Full Year,NaN,NaN,447,478,-31,NaN
2349,2022-2023,1250,Joseph W. Catharine School,Elementary School,October 1 Enrollment,NaN,NaN,409,409,0,NaN
2463,2022-2023,1250,Joseph W. Catharine School,Elementary School,% of Students Receiving Zero Out-of-School Sus...,447.0,447.0,100,99.4,0.6,Improving

In [64]:
# Pivot the elementary_school_metrics_df DataFrame to create one row for each school 
es_metrics_df = elementary_school_metrics_df.pivot_table(
    index = ['accountability_year', 'school_id', 'school_name', 'report_type'],
    columns = 'metric', 
    values = 'metric_score',
    aggfunc='first'
).reset_index()

es_metrics_df.head()

metric,accountability_year,school_id,school_name,report_type,# of Students Served Over the Full Year,% of Students Attending at Least 90% of Instructional Days,% of Students Receiving Zero Out-of-School Suspensions,% of Teachers Attending at Least 90% of Instructional Days,% of Teachers Rated as Distinguished,% of Teachers Rated as Proficient,...,"PSSA ELA: % of Students Proficient or Advanced, Grade 3","PSSA ELA: % of Students Proficient or Advanced, Grades 3-8","PSSA Math: % of Students Below Basic, Grade 3","PSSA Math: % of Students Below Basic, Grades 3-8","PSSA Math: % of Students Proficient or Advanced, Grade 3","PSSA Math: % of Students Proficient or Advanced, Grades 3-8","PSSA Science: % of Students Below Basic, Grades 4-8","PSSA Science: % of Students Proficient or Advanced, Grades 4-8","Percent of Metrics Improving, All Students",Year-to-Year Teacher Retention
0,2022-2023,1250,Joseph W. Catharine School,Elementary School,447,66.7,100,97,0,96.4,...,18.9,20,67.6,64,18.9,14.8,35.4,33.9,61.5,79.4
1,2022-2023,1380,Thomas G. Morton School,Elementary School,424,59,96.5,85.7,0,84.6,...,25.4,24.6,80.3,70.4,6.6,8.3,29.8,40.4,92.3,85.3
2,2022-2023,1390,Samuel Powel School,Elementary School,317,79.5,99.7,95.7,5.9,94.1,...,66,56.1,21.3,22.5,55.3,51,17.7,62.8,76.9,81.8
3,2022-2023,1400,John M. Patterson School,Elementary School,420,57.6,97.6,79.2,0,100,...,20.3,22.8,64.2,58.2,11.9,14.2,20.9,44.8,38.5,84
4,2022-2023,2320,Stephen Girard School,Elementary School,336,54.2,100,100,22.2,77.8,...,36.4,34.7,46.3,46.4,26.9,28,15.8,52.6,92.3,91.3

In [65]:
# List the es_metrics_df columns
# es_metrics_df.columns

In [66]:
# Create a list with desireds column order
es_columns = [
    'accountability_year', 
    'school_id', 
    'school_name', 
    'report_type', 
    'Admission Type', 
    '# of Students Served Over the Full Year', 
    'October 1 Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grade 3',
    'PSSA ELA: % of Students Below Basic, Grades 3-8',
    'PSSA ELA: % of Students Proficient or Advanced, Grade 3',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Math: % of Students Below Basic, Grade 3',
    'PSSA Math: % of Students Below Basic, Grades 3-8',
    'PSSA Math: % of Students Proficient or Advanced, Grade 3',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8',
    'PSSA Science: % of Students Below Basic, Grades 4-8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8',
    'Percent of Metrics Improving,  All Students', 
    '% of Students Attending at Least 90% of Instructional Days', 
    '% of Students Receiving Zero Out-of-School Suspensions'
]

# Reorder the DataFrame columns
es_metrics_df = es_metrics_df[es_columns]

In [67]:
# Rename the Columns with compatible formatting 
es_metrics_df = es_metrics_df.rename(columns={
    'accountability_year': 'Year', 
    'school_id': 'school_id', 
    'school_name': 'School_Name', 
    'report_type': 'Report_Type', 
    'Admission Type': 'Admission_Type', 
    '# of Students Served Over the Full Year': 'Number_Students_Served_Full_Year', 
    'October 1 Enrollment': 'October_1_Enrollment', 
    'PSSA ELA: % of Students Below Basic, Grade 3': 'PSSA_ELA_Percent_Students_Below_Basic_Grade_3',
    'PSSA ELA: % of Students Below Basic, Grades 3-8': 'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA ELA: % of Students Proficient or Advanced, Grade 3': 'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA ELA: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Math: % of Students Below Basic, Grade 3': 'PSSA_Math_Percent_Students_Below_Basic_Grade_3',
    'PSSA Math: % of Students Below Basic, Grades 3-8': 'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA Math: % of Students Proficient or Advanced, Grade 3': 'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA Math: % of Students Proficient or Advanced, Grades 3-8': 'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA Science: % of Students Below Basic, Grades 4-8': 'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA Science: % of Students Proficient or Advanced, Grades 4-8': 'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent of Metrics Improving,  All Students': 'Percent_Metrics_Improving_All_Students', 
    '% of Students Attending at Least 90% of Instructional Days': 'Percent_Students_Attending_at_Least_90_Percent', 
    '% of Students Receiving Zero Out-of-School Suspensions': 'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
})

es_metrics_df.head()

metric,Year,school_id,School_Name,Report_Type,Admission_Type,Number_Students_Served_Full_Year,October_1_Enrollment,PSSA_ELA_Percent_Students_Below_Basic_Grade_3,PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3,PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8,PSSA_Math_Percent_Students_Below_Basic_Grade_3,PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8,PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3,PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8,PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8,PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8,Percent_Metrics_Improving_All_Students,Percent_Students_Attending_at_Least_90_Percent,Percent_Students_Receiving_Zero_Out_of_School_Suspensions
0,2022-2023,1250,Joseph W. Catharine School,Elementary School,Catchment,447,409,35.1,36.5,18.9,20,67.6,64,18.9,14.8,35.4,33.9,61.5,66.7,100
1,2022-2023,1380,Thomas G. Morton School,Elementary School,Catchment,424,367,35.6,38.9,25.4,24.6,80.3,70.4,6.6,8.3,29.8,40.4,92.3,59,96.5
2,2022-2023,1390,Samuel Powel School,Elementary School,Catchment,317,295,8.5,14.3,66,56.1,21.3,22.5,55.3,51,17.7,62.8,76.9,79.5,99.7
3,2022-2023,1400,John M. Patterson School,Elementary School,Catchment,420,355,39.1,39.8,20.3,22.8,64.2,58.2,11.9,14.2,20.9,44.8,38.5,57.6,97.6
4,2022-2023,2320,Stephen Girard School,Elementary School,Catchment,336,291,25.8,29.8,36.4,34.7,46.3,46.4,26.9,28,15.8,52.6,92.3,54.2,100

In [68]:
es_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 20 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                56 non-null     object
 1   school_id                                                           56 non-null     int64
 2   School_Name                                                         56 non-null     object
 3   Report_Type                                                         56 non-null     object
 4   Admission_Type                                                      56 non-null     object
 5   Number_Students_Served_Full_Year                                    56 non-null     object
 6   October_1_Enrollment                                                56 non-null     object
 7   PSSA_ELA_Percent_Students_Below_Basic_Grade_3                       56 non-null     object
 8   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 56 non-null     object
 9   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3            56 non-null     object
 10  PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      56 non-null     object
 11  PSSA_Math_Percent_Students_Below_Basic_Grade_3                      56 non-null     object
 12  PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                56 non-null     object
 13  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3           56 non-null     object
 14  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     56 non-null     object
 15  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             56 non-null     object
 16  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  56 non-null     object
 17  Percent_Metrics_Improving_All_Students                              56 non-null     object
 18  Percent_Students_Attending_at_Least_90_Percent                      56 non-null     object
 19  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           56 non-null     object
dtypes: int64(1), object(19)
memory usage: 8.9+ KB

In [69]:
# List the es_metrics_df columns
# es_metrics_df.columns

In [70]:
# List of columns to convert
es_columns_to_convert = [
    'Number_Students_Served_Full_Year', 
    'October_1_Enrollment',
    'PSSA_ELA_Percent_Students_Below_Basic_Grade_3',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Below_Basic_Grade_3',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8',
    'Percent_Metrics_Improving_All_Students',
    'Percent_Students_Attending_at_Least_90_Percent',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions'
]

# Apply pd.to_numeric to convert strings to 'NaN'
es_metrics_df[es_columns_to_convert] = es_metrics_df[es_columns_to_convert].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# Set the datatypes
es_metrics_df = es_metrics_df.astype({    
    'Number_Students_Served_Full_Year': 'int64', 
    'October_1_Enrollment': 'int64',
    'PSSA_ELA_Percent_Students_Below_Basic_Grade_3': 'float64',
    'PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3': 'float64',
    'PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Below_Basic_Grade_3': 'float64',
    'PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8': 'float64',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3': 'float64',
    'PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8': 'float64',
    'PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8': 'float64',
    'PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8': 'float64',
    'Percent_Metrics_Improving_All_Students': 'float64',
    'Percent_Students_Attending_at_Least_90_Percent': 'float64',
    'Percent_Students_Receiving_Zero_Out_of_School_Suspensions': 'float64'
})

In [71]:
es_metrics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 20 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                56 non-null     object
 1   school_id                                                           56 non-null     int64
 2   School_Name                                                         56 non-null     object
 3   Report_Type                                                         56 non-null     object
 4   Admission_Type                                                      56 non-null     object
 5   Number_Students_Served_Full_Year                                    56 non-null     int64
 6   October_1_Enrollment                                                56 non-null     int64
 7   PSSA_ELA_Percent_Students_Below_Basic_Grade_3                       54 non-null     float64
 8   PSSA_ELA_Percent_Students_Below_Basic_Grades_3_to_8                 54 non-null     float64
 9   PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grade_3            54 non-null     float64
 10  PSSA_ELA_Percent_Students_Proficient_or_Advanced_Grades_3_to_8      54 non-null     float64
 11  PSSA_Math_Percent_Students_Below_Basic_Grade_3                      54 non-null     float64
 12  PSSA_Math_Percent_Students_Below_Basic_Grades_3_to_8                54 non-null     float64
 13  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grade_3           54 non-null     float64
 14  PSSA_Math_Percent_Students_Proficient_or_Advanced_Grades_3_to_8     54 non-null     float64
 15  PSSA_Science_Percent_Students_Below_Basic_Grades_4_to_8             54 non-null     float64
 16  PSSA_Science_Percent_Students_Proficient_or_Advanced_Grades_4_to_8  54 non-null     float64
 17  Percent_Metrics_Improving_All_Students                              54 non-null     float64
 18  Percent_Students_Attending_at_Least_90_Percent                      56 non-null     float64
 19  Percent_Students_Receiving_Zero_Out_of_School_Suspensions           56 non-null     float64
dtypes: float64(13), int64(3), object(4)
memory usage: 8.9+ KB

In [72]:
# Export to csv 
es_metrics_df.to_csv('Outputs_School_Metrics/elementary_school_metric_scores.csv', index=False)